### ISSUE TITLE
Consul-ESM: External node checks disappear after re-registration of nodes

### ISSUE THREAD

**Issue by hsharma8693** [hashicorp/consul-esm#119]
**Describe the bug**
Consul ESM shows no node checks after re-registering nodes.

**To Reproduce**
Following the [Learning Guide] (https://learn.hashicorp.com/tutorials/consul/service-registration-external-services?in=consul/developer-discovery) I build my setup. Tried following steps:-

* Started Consul agent in -dev mode.
* Register an external service to consul with health checks by running command `curl --request PUT --data @external.json localhost:8500/v1/catalog/register`, refer to the configuration of external service file. 

```
$ cat external.json

{
  "Node": "External-Node",
  "Address": "192.168.64.32",
  "NodeMeta": {
    "external-node": "true",
    "external-probe": "true"
  },
  "Service": {
    "ID": "Python-HTTP",
    "Service": "Python",
    "Port": 80
  },
  "Checks": [
    {
      "Name": "tcp-check",
      "status": "critical",
      "Definition": {
        "TCP": "192.168.64.32:80",
        "interval": "30s"
      },
      "ServiceID": "Python-HTTP",
      "CheckID": "service:Python"
    }
  ]
}

```

* Started consul-esm agent, initially it perform health checks for node "External-Node" and on Consul UI status of both service and node was okay.

```
$ curl localhost:8500/v1/health/node/External-Node
[
    {
        "Node": "External-Node",
        "CheckID": "externalNodeHealth",
        "Name": "External Node Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Node alive or reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {},
        "CreateIndex": 29,
        "ModifyIndex": 160
    },
    {
        "Node": "External-Node",
        "CheckID": "service:Python",
        "Name": "tcp-check",
        "Status": "passing",
        "Notes": "",
        "Output": "TCP connect 192.168.64.32:80: Success",
        "ServiceID": "Python-HTTP",
        "ServiceName": "Python",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {
            "Interval": "30s",
            "TCP": "192.168.64.32:80"
        },
        "CreateIndex": 24,
        "ModifyIndex": 2963
    }
]

```

* Once we deregister node and re-register it back, Consul-ESM agent could not update the health check status and flagging node check as "No health check". 

```
$ cat external-node-deregister.json 

{
 "Node": "External-Node"
}
```

**De-Registering Node**

` $ curl --request PUT --data @external-node-deregister.json http://localhost:8500/v1/catalog/deregister `

**Re-register Service & Node**

` curl --request PUT --data @external.json localhost:8500/v1/catalog/register ` 

**External-Node health check is missing**

```
$ curl localhost:8500/v1/health/node/External-Node1
[
    {
        "Node": "External-Node",
        "CheckID": "service:Python1",
        "Name": "tcp-check",
        "Status": "passing",
        "Notes": "",
        "Output": "TCP connect 192.168.64.32:80: Success",
        "ServiceID": "Python-HTTP1",
        "ServiceName": "Python",
        "ServiceTags": [],
        "Type": "",
        "Interval": "",
        "Timeout": "",
        "ExposedPort": 0,
        "Definition": {
            "Interval": "30s",
            "TCP": "192.168.64.32:80"
        },
        "CreateIndex": 3632,
        "ModifyIndex": 3642
    }
]

```

**Expected behavior**
In absence of this bug, Consul ESM should do health checks for nodes once we re-register the nodes, and do the real-time update of catalog. 

**Environment:** 
- Product Version:
  Checked with consul-esm version v0.6.0 and v0.5.0 

- Server configuration file(s) and read output of any relevant mount/role/etc configuration: 
   Have attached configuration files and read output above.

**Is there a workaround?**
For consul-esm to pick re-registered node health check again, we had to re-run consul-esm agent.

[edit: changed "External-Node1" to "External-Node" in deregistration to match up with earlier name usage]

**Comment by eikenb** [comment]
FYI. I've reproduced this and am looking into it now.
