### ISSUE TITLE
udp ping mode erroring

### ISSUE THREAD

**Issue by far-blue** [hashicorp/consul-esm#13]
Hello :) Thanks for this project - it was exactly what I was looking for!

In UDP ping mode I kept getting a socket error regarding permissions. Even using setcap didn't seem to help. Switching to socket mode (and using setcap) fixes things.

**Comment by kyhavlov** [comment]
That sounds a lot like this issue: https://github.com/tatsushid/go-fastping/issues/25

Can you try changing that setting and seeing if that fixes it?

**Comment by far-blue** [comment]
I've tested and am getting the sysctl return of `1 0` so it looks like this is the problem. I'll update my docker image and test further on tuesday when I'm back in the office.

**Comment by kyhavlov** [comment]
I'm going to close this as it looks like that kernel setting was the issue. If anyone is still having this problem and it's unrelated to that setting, feel free to comment here or open a new issue.
