### ISSUE TITLE
Compatability with consul replicate?

### ISSUE THREAD

**Issue by hugadams** [hashicorp/consul-esm#14]
Hi,

My company is a consul enterprise subscriber and we use consul-esm internally for service discovery across our infrastructure.  Do you know offhand if consul-esm is compatible with consul-replicate?  https://github.com/hashicorp/consul-replicate

I imagine consul-replicate is tested with typical deployments of consul-server, but would you expect it to be compatible with consul-esm?  And if so, are there any special considerations that come to mind?

Thanks

**Comment by banks** [comment]
consul-replicate only replicates KV store state in an asynchronous (e.g. causally consistent but no strongly consistent) way. It only allows a single datacenter to be the "master" that replicated KVs are written to.

Consul-esm does use the KV store to manage locks and it's highly inadvisable to replicate locks with consul-replicate as that tool removes all consistency/safety guarantees that locks rely on, and the locks can't be obtained/written from the follower DC anyway as all writes (including lock acquisition) must go to the master DC.

That said, provided you don't replicate the locks ESM creates or at least you don't rely on ESM instances in multiple datacenters coordinating on the replicated locks then I don't see any reason they would be incompatible.

For future reference, questions like this are great candidates for the [Google group](https://groups.google.com/group/consul-tool/).
