### ISSUE TITLE
Deadlock in check update code

### ISSUE THREAD

**Issue by Foxlik** [hashicorp/consul-esm#159]
Thanks to the issue #158 I found a deadlock occuring in Consul ESM. For me it actually happens pretty often - under 15 minutes after starting ESM.

There are two goroutines involved:

**1. Consul ESM watchNodeList:**
- found a change to the check specification,
- locked the checkRunner mutex (at [consul-esm/check.go:209](https://github.com/hashicorp/consul-esm/blob/93a8ff16e34ffdcf927159f78d495c7859badc46/check.go#L209))
- attempts to stop the check
- conul code waits for the running check (waitGroup stopWg) to finish (at [consul/agent/checks/check.go:427](https://github.com/hashicorp/consul/blob/f1054dada9aecf2efb9a2d68b21719561200d5fd/agent/checks/check.go#L427))
- in the end it's holding checkRunner locked in Consul-ESM and waits for stopWg in Consul
```
runtime.gopark(proc.go:362)
runtime.goparkunlock(proc.go:367)
runtime.semacquire1(sema.go:144)
sync.runtime_Semacquire(sema.go:56)
sync.(*WaitGroup).Wait(waitgroup.go:136)
github.com/hashicorp/consul/agent/checks.(*CheckHTTP).Stop(check.go:427)
main.(*CheckRunner).updateCheckHTTP(check.go:131)
main.(*CheckRunner).UpdateChecks(check.go:240)
main.(*Agent).watchHealthChecks(agent.go:481)
main.(*Agent).watchNodeList.func2(agent.go:328)
runtime.goexit(asm_amd64.s:1571)
main.(*Agent).watchNodeList(agent.go:328)
```
**2. Consul Agent CheckHTTP:**
- adds itself into the stopWg waitgroup (at [consul/agent/checks/check.go:413](https://github.com/hashicorp/consul/blob/f1054dada9aecf2efb9a2d68b21719561200d5fd/agent/checks/check.go#L413))
- attempts to update the status calling StatusHandler => Consul ESM UpdateCheck (at [consul/agent/checks/check.go:1086](https://github.com/hashicorp/consul/blob/f1054dada9aecf2efb9a2d68b21719561200d5fd/agent/checks/check.go#L1086))
- UpdateCheck tries to acquire the CheckRunner lock (at [consul-esm/check.go:305](https://github.com/hashicorp/consul-esm/blob/93a8ff16e34ffdcf927159f78d495c7859badc46/check.go#L305))
- in the end it keeps the stopWg in Consul from releasing and is waiting for the CheckRunner mutex in Consul ESM to be released 

```
runtime.gopark(proc.go:362)
runtime.goparkunlock(proc.go:367)
runtime.semacquire1(sema.go:144)
sync.runtime_SemacquireMutex(sema.go:71)
sync.(*Mutex).lockSlow(mutex.go:162)
sync.(*Mutex).Lock(mutex.go:81)
sync.(*RWMutex).Lock(rwmutex.go:139)
main.(*CheckRunner).UpdateCheck(check.go:305)
github.com/hashicorp/consul/agent/checks.(*StatusHandler).updateCheck(check.go:1086)
github.com/hashicorp/consul/agent/checks.(*CheckHTTP).check(check.go:505)
github.com/hashicorp/consul/agent/checks.(*CheckHTTP).run(check.go:439)
github.com/hashicorp/consul/agent/checks.(*CheckHTTP).Start.func3(check.go:414)
runtime.goexit(asm_amd64.s:1571)
github.com/hashicorp/consul/agent/checks.(*CheckHTTP).Start(check.go:414)
```

I'm no Go expert, so I dare not attempt to fix this async code myself. I'd be grateful if someone could do something about it.

**Comment by cbroglie** [comment]
We're running into the same issue after attempting to upgrade from 0.5.0 to 0.6.1.

**Comment by eikenb** [comment]
Thanks for the report @Foxlik and bump @cbroglie. Sorry it took so long but I'm looking into this now.

**Comment by eikenb** [comment]
I've been able to reproduce it but the easy fix idea didn't pan out. This might take a bit.

**Comment by eikenb** [comment]
After playing around with the idea of gutting and refactoring the whole section I came up with another relatively easy, low impact (as it doesn't change a lot) fix. Changing the 2 maps of stored consul checks (checks HTTP, checksTCP) to use sync.Map and keep the mutex for the others. This lets me remove the lock from the Stop call and eliminates the deadlock. PR in a few.

**Comment by Foxlik** [comment]
Thanks @eikenb for fixing that!
