### ISSUE TITLE
Feature request: Official docker image

### ISSUE THREAD

**Issue by groggemans** [hashicorp/consul-esm#19]
It would be nice to have an "official" docker image. (just like consul-template already has one)
Having a pre-build image makes it even easier to get started with this little service.

**Comment by mitchellh** [comment]
We'll have this soon, #20 is our first step towards that.

**Comment by dekimsey** [comment]
On that note, being able to specify config via Environment variables (ala CONSUL_LOCAL_CONFIG) would be _extremely_ helpful.

**Comment by johnjelinek** [comment]
@mitchellh: updates on this?

**Comment by shellfu** [comment]
This would be nice

**Comment by nvx** [comment]
Is there anything blocking this? Even without CONSUL_LOCAL_CONFIG or the like it would still be super handy to have an official image being pushed.

**Comment by lornasong** [comment]
Apologies for the delay. Thank you to everyone for the interest they’ve expressed! Nothing is blocking this right now. Just as an update, our team is aware that this is an important feature, and we recently prioritized and determined allocated time for working on this. Thanks!

**Comment by eikenb** [comment]
Docker image will be published with this upcoming, 0.6.0, release. Everything is merged and should be good to go.
I'll close this post release when it's available on docker hub.

**Comment by eikenb** [comment]
Docker image published. Please file a new issue if there are any problems with it. Thanks!
