### ISSUE TITLE
Resource Leak in release 0.7.0

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/consul-esm#194]
### Consul version
`Consul v1.14.2` with `consul-esm v0.7.0 (b0b2b38)`

### Operating system and Environment details
Docker containers running on Debian 11 ARM64

### Issue
There appears to be a memory leak with the Consul-ESM service. typical memory usage is around 10MB but over a number of hours it exceeds 32MB and my system kills it. (OOM killer triggered)

<img width="1198" alt="OOM-killed-consul-esm" src="https://user-images.githubusercontent.com/6336384/207208161-00cbdfc0-1181-41cf-82b9-cadf17ca0f75.png">

### Reproduction steps
I ran the container using attached nomad job file.
[esm.nomad.txt](https://github.com/hashicorp/consul-esm/files/10213596/esm.nomad.txt)

#### Expected Result
I hope it would run with a consistent memory footprint like the previous version (about 10MB for v0.6.2)

#### Actual Result
OOM-killed, the excessive memory usage triggered the scheduler to kill it.

**Comment by tristanmorgan** [comment]
Go routines seems to be a runaway too.

<img width="1198" alt="consul-esm-go-routines" src="https://user-images.githubusercontent.com/6336384/207216659-8e57cdbd-1989-4247-a006-f316a46a1c09.png">

**Comment by tristanmorgan** [comment]
```
goroutine 833 [chan receive, 42 minutes]:
main.(*Agent).getHealthChecks.func1()
	/home/runner/work/consul-esm/consul-esm/agent.go:513 +0x30
created by main.(*Agent).getHealthChecks
	/home/runner/work/consul-esm/consul-esm/agent.go:512 +0x1f8

goroutine 715 [chan receive, 45 minutes]:
main.(*Agent).getHealthChecks.func1()
	/home/runner/work/consul-esm/consul-esm/agent.go:513 +0x30
created by main.(*Agent).getHealthChecks
	/home/runner/work/consul-esm/consul-esm/agent.go:512 +0x1f8

goroutine 788 [chan receive, 43 minutes]:
main.(*Agent).getHealthChecks.func1()
	/home/runner/work/consul-esm/consul-esm/agent.go:513 +0x30
created by main.(*Agent).getHealthChecks
	/home/runner/work/consul-esm/consul-esm/agent.go:512 +0x1f8

goroutine 697 [chan receive, 46 minutes]:
main.(*Agent).getHealthChecks.func1()
	/home/runner/work/consul-esm/consul-esm/agent.go:513 +0x30
created by main.(*Agent).getHealthChecks
	/home/runner/work/consul-esm/consul-esm/agent.go:512 +0x1f8
```

**Comment by tristanmorgan** [comment]
Hi @eikenb 
Just bringing this to your attention. I think you'd be the one with the most familiarity of the code that changed.
Regards,

Tristan

**Comment by eikenb** [comment]
Don't have time to do a lot of work on this (I'm moving to different a different project here) but it seems pretty simple... I've posted a PR for this and if you could take a look/test it I could get it merged and do a release quickly.

https://github.com/hashicorp/consul-esm/pull/196

**Comment by tristanmorgan** [comment]
Thank you!
