### ISSUE TITLE
Run consul-esm without ping

### ISSUE THREAD

**Issue by derek-cordeiro** [hashicorp/consul-esm#41]
I'm testing consul-esm as a means to register and monitor external services whose "Node" is not pingable(icmp/udp). How do I skip "ping" checks and tell consul-esm to run the HTTP/TCP health checks defined? Or am I missing something?

**Comment by hvindin** [comment]
When I've registered services on "Nodes" which we can't UDP or ICMP ping I've just set 

```json
"NodeMeta": {
  "external-node": "true",
  "external-probe": "false"
}
```

From my knowledge external-probe indicates that the node should be health checked via ICMP or UDP, so simply setting it to false seems to switch off that particular health check.

**Comment by derek-cordeiro** [comment]
Thanks @hvindin I was trying to use consul-esm to monitor managed services such as AWS RDS(add/remove slaves, etc). From what I understand, consul-esm does not support script checks as consul agent does so I've not tried anything further.

Thanks for the response though!
