### ISSUE TITLE
Add a mode to not require root privileges

### ISSUE THREAD

**Issue by myuen4** [hashicorp/consul-esm#5]
We noticed that the consul-esm requires root access in order to ping nodes that it monitors. Running the ESM with root privileges is not really reasonable in most cases.

A log sample:

2018/02/23 06:52:20 [WARN] could not ping node "<node>": listen ip4:icmp : socket: operation not permitted

The ESM uses go-fastping to conduct this, which has the ability to ping over UDP without root privileges; can the default network mode be set to UDP or can an option be exposed to we can change it to udp?

Relevant links:
- https://github.com/tatsushid/go-fastping/issues/8
- https://github.com/tatsushid/go-fastping/commit/41b7495ae337675151c762cbafafdb846021c34a
- https://godoc.org/golang.org/x/net/icmp#ListenPacket

**Comment by myuen4** [comment]
Can this change be controlled from an option the config?

**Comment by pearkes** [comment]
@myuen4 Can you describe your use-case a bit? From our point of view not requiring root is preferable in most cases.

**Comment by myuen4** [comment]
Sure, I think there are a couple of reasons why this might be sensible

 - The doc's say, "Currently only Darwin and Linux support this." so if this ever got deployed outside of Darwin / Linux "udp" won't work.
 - Our specific use case is one the doc's don't reference, we discovered "udp" requires adding "net.ipv4.ping_group_range=<uid> <uid>" to sysctl.conf. It might be easier to use sud setcap to allow raw sockets, and operates on the specific binary instead of on the entire user account.

**Comment by kyhavlov** [comment]
Added an option (`ping_type`) for this in 0cd2437.
