### ISSUE TITLE
Graceful terminate on SIGTERM

### ISSUE THREAD

**Issue by myuen4** [hashicorp/consul-esm#6]
We noticed that the consul-esm leaves gracefully only when a SIGINT is issued. Can a handler for SIGTERM be added, SIGINT is generally only the norm for interactive use.

Relevant code:

https://github.com/hashicorp/consul-esm/blob/master/main.go#L105-L113

**Comment by myuen4** [comment]
This change seems to be picking up all signals now, I think we are just after SIGTERM? Some of the other signals are going to cause a few issues...

e.g. SIGWINCH
The SIGWINCH signal is sent to a process when its controlling terminal changes its size (a window change).[13]

2018/03/13 13:17:41 [INFO] Waiting to obtain leadership...
2018/03/13 13:17:42 [INFO] Caught signal: window changed, shutting down...
2018/03/13 13:17:43 [INFO] Caught signal: window changed, shutting down...
2018/03/13 13:17:48 [INFO] Caught signal: window changed, shutting down...

**Comment by banks** [comment]
Yeah I'd suggest we stick to just SIGINT and SIGTERM for now. Anything else is likely to cause issues - signals are a wild west outside of those few that are well-defined. Stuff like terminal window size change, child process dying, process being paused or put into background etc. will all cause it to exit now which is not what we want.

@kyhavlov sound reasonable?

**Comment by banks** [comment]
(I think this should be re-opened to remind us, I'm waiting on access to be able to do that myself).
