### ISSUE TITLE
Add support for health checks which require mTLS

### ISSUE THREAD

**Issue by cbroglie** [hashicorp/consul-esm#72]
We'd like to use ESM to monitor external services which require client authentication via mTLS. The Consul agent supports a version of this via the `enable_agent_tls_for_checks` option, but for ESM it would be nice to configure separate credentials for health checks, rather than reusing the ones for Consul communication. It's fine to use a single key pair for all health checks, however.

**Comment by lornasong** [comment]
Closing. Resolved with https://github.com/hashicorp/consul-esm/pull/81
