### ISSUE TITLE
Structured logging support

### ISSUE THREAD

**Issue by edevil** [hashicorp/consul-esm#82]
In the spirit of https://github.com/hashicorp/consul/pull/7130, I think it would be great if ESM also supported structured logging.

What do you think of doing the same thing here?

**Comment by edevil** [comment]
Could you tell me how to enable this currently @lornasong ? I see no flag for it... /cc @varnson

**Comment by lornasong** [comment]
@edevil thanks for the question! This is my fault! @ varnson's PR is for converting the logging to hclog only and does not include the structured logs option. I will reopen this issue. Apologies for the confusion and thanks for raising this!
