### ISSUE TITLE
Deadlock in go-ping

### ISSUE THREAD

**Issue by mikeyyuen** [hashicorp/consul-esm#86]
It looks like go-fastping was replaced with go-ping last year [here](https://github.com/hashicorp/consul-esm/pull/46).

However go-ping seems to have deadlock issues at scale.

https://github.com/go-ping/ping/pull/85
https://github.com/go-ping/ping/issues/77

We have been observing when we upgraded to this latest version of the code we picked up the go-ping change. When we scale it up we see a memory leak that also leaks go-routines, raw sockets & file handles.

When we apply something like [this patch](https://github.com/tsarstva/go-ping/commit/49e186a441c93167c2b56f87e99dd6eeb827852f) into a test environment we are able to see that the issue goes away.

Charts below show the difference when we deployed the change at about 3pm on the 28th. (You can also see a previous deploy at 7am which did not have the fix and shows the resource leek happening quickly after a restart.)

<img width="1248" alt="memory_and_swap_48_hours" src="https://user-images.githubusercontent.com/7327973/94588509-e3bd5080-027b-11eb-986a-4f10e0b0118c.png">
<img width="1223" alt="goroutines_48_hours" src="https://user-images.githubusercontent.com/7327973/94588514-e4ee7d80-027b-11eb-8cfa-fbbed9054e9c.png">
<img width="1255" alt="file_handles_48_hours" src="https://user-images.githubusercontent.com/7327973/94588517-e61faa80-027b-11eb-8530-24c5f8bf6442.png">

The go-ping library does have a suggested fix https://github.com/go-ping/ping/pull/85, however that fix will still deadlock at scale. I think to fix it properly the `wg.Wait()` calls in [this](https://github.com/go-ping/ping/blob/master/ping.go#L346) block need to be replaced with something async (a channel) so that the loop does not ever block the `recv` channel.

That partial improvement PR https://github.com/go-ping/ping/pull/85 has also beem awaiting merge since March.

Question for HashiCorp is how to proceed? Do we want to

1. Revert to go-fastping (probably not it will likely still have the issues that caused us to pick up go-ping).
2. Submit a patch to go-ping (although that seems like it could take a while).
3. Do something else? Fork the lib again? Embed the pinger directly here?

**Comment by eikenb** [comment]
Thanks @mikeyyuen for reporting this. We're evaluating our options and will try to get to this soon.

**Comment by lornasong** [comment]
@mikeyyuen, thanks again for raising this issue and investigating go-ping. @eikenb and I spoke about this and here’s what we’re thinking:

Re: revert to go-fastping: agree that this will revert the previous issue. It looks like they’ve had some scaling issues as well and haven’t been maintained since 2016.

Re: submit a patch to go-ping: the repo looks maintained - https://github.com/go-ping/ping/pull/85 looks approved by the go-ping team and they requested tests a couple weeks ago. Agree though that we could potentially wait a long time for this so we’ll still want to 'do something else'. If your team has capacity to submit an issue/pr though, it could still be beneficial for the community.

Re: Do something else: we’re thinking that this is the best way to proceed. It would be great to implement ping in ESM using the icmp library so that it would be a pared down version of go-ping implementing only the features we need at this point.

Let us know what you think! Thanks.

**Comment by mikeyyuen** [comment]
I think a paird down version of go-ping might make sense, that might be something we could contribute if your interested? How does HashiCorp prefer to handle attribution in such cases, any pinger in the consul-esm would be inspired / derived from go-ping which is MIT, I believe that reqires retention of the original copyright?

**Comment by lornasong** [comment]
@mikeyyuen - yes, we would definitely welcome contributions to make this happen! Thanks for raising the copyright issue. I just reached out to our legal team to confirm and make sure everything looks ok from a legal standpoint. I'll follow up here as soon as I hear from them.

**Comment by lornasong** [comment]
@mikeyyuen, I heard back from our legal team and, just as you mentioned, they said that esm's ping version contains substantial portions of the original work (which seems likely) we can only distribute it if we retain go-ping's copyright in the license. We should include the license with the copyright notice ( “Copyright (c) 2016 Cameron Sparr”). Let me know if you have any questions!

**Comment by chenlujjj** [comment]
@mikeyyuen Do you ever noticed any CPU usage issue when using go-ping in scale ? like this: https://github.com/go-ping/ping/issues/125

**Comment by SuperQ** [comment]
Hey, go-ping maintainer here. We're happy to accept patches now that we've got additional maintainers available to do reviews.

**Comment by eikenb** [comment]
Sorry for the long delay resolving this. All the issues mentioned above have been addressed upstream. I'm going to bump the go-ping dependency version to 1.0.0 which should include all the fixes.

I will push up the PR with this in a minute and will close this issue on merging it. Please chime in if you see any issue with that plan. Thanks.
