### ISSUE TITLE
Expose HTTP endpoint for metrics scraping (Prometheus)

### ISSUE THREAD

**Issue by edevil** [hashicorp/consul-esm#89]
Metrics were added in https://github.com/hashicorp/consul-esm/pull/67 and a Prometheus sink is supported to collect them. However, we have no way to scrape them from the ESM application.

The usual way this is done is by configuring Prometheus to scrape an HTTP endpoint of the application that exposes these metrics on a certain path, but ESM has no such endpoint. There is also the pushgateway approach but a `PrometheusPushSink` is not configured and is also not the recommended approach as seen here https://prometheus.io/docs/practices/pushing/.

The telemetry lib being used is the one from Consul, but in this case the agent has an http endpoint and exposes the metrics here https://github.com/hashicorp/consul/blob/1b413b0444fe91a30bf18989fe8c668a767c9c8a/agent/agent_endpoint.go#L151. I propose that we make ESM export an http interface just for collecting metrics when Prometheus telemetry is enabled (`prometheus_retention_time` > 0).

**Comment by lornasong** [comment]
@edevil thanks for writing this up and the helpful information around PrometheusSink and push gateway. I think your proposal of exposing a metrics endpoint when Prometheus is enabled sounds like a good idea. It'll be helpful for our community members who also use Prometheus!
